### ISSUE TITLE
Bump NodeJS version

### ISSUE THREAD

**Issue by idobiran11** [hmarr/debug-action#8]
Hey,
I would be glad if you could bump the nodejs version to 20 seeing as 16 will be deprecated soon. 
![Screenshot 2024-02-01 at 13 56 43](https://github.com/hmarr/debug-action/assets/112331505/0752b9fd-f3ad-4ac8-968f-6a1192fab116)

**Comment by hmarr** [comment]
Fixed by #7 and released in v3.0.0
